2021-12-19 11:51:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "SELECT POINTOFINT0_.ID AS ID1_1_0_, CATEGORY2_.ID AS ID1_0_1_, POINTOFINT0_.COVER_PHOTO AS COVER_PH2_1_0_, POINTOFINT0_.DATE AS DATE3_1_0_, POINTOFINT0_.DESCRIPTION AS DESCRIPT4_1_0_, POINTOFINT0_.LOCATION AS LOCATION5_1_0_, POINTOFINT0_.NAME AS NAME6_1_0_, POINTOFINT0_.PHOTO2 AS PHOTO7_1_0_, POINTOFINT0_.PHOTO3 AS PHOTO8_1_0_, CATEGORY2_.NAME AS NAME2_0_1_, LISTCATEGO1_.LIST_POINT_OF_INTEREST_ID AS LIST_POI1_2_0__, LISTCATEGO1_.LIST_CATEGORY_ID AS LIST_CAT2_2_0__ FROM POINT_OF_INTERES POINTOFINT0_ INNER JOIN POINT_OF_INTERES_LIST_CATEGORY LISTCATEGO1_ ON POINTOFINT0_.ID=LISTCATEGO1_.LIST_POINT_OF_INTEREST_ID INNER JOIN CATEGORY CATEGORY2_ ON LISTCATEGO1_.LIST_CATEGORY_ID=CATEGORY2_.ID CROSS JOIN POINT_OF_INTERES_LIST_CATEGORY LISTCATEGO3_, CATEGORY CATEGORY4_ WHERE POINTOFINT0_.ID=LISTCATEGO3_.LIST_POINT_OF_INTEREST_ID AND LISTCATEGO3_.LIST_CATEGORY_ID=CATEGORY4_.ID AND (? IN (.[*]))"; se esperaba "NOT, EXISTS, INTERSECTS, UNIQUE"
Syntax error in SQL statement "SELECT POINTOFINT0_.ID AS ID1_1_0_, CATEGORY2_.ID AS ID1_0_1_, POINTOFINT0_.COVER_PHOTO AS COVER_PH2_1_0_, POINTOFINT0_.DATE AS DATE3_1_0_, POINTOFINT0_.DESCRIPTION AS DESCRIPT4_1_0_, POINTOFINT0_.LOCATION AS LOCATION5_1_0_, POINTOFINT0_.NAME AS NAME6_1_0_, POINTOFINT0_.PHOTO2 AS PHOTO7_1_0_, POINTOFINT0_.PHOTO3 AS PHOTO8_1_0_, CATEGORY2_.NAME AS NAME2_0_1_, LISTCATEGO1_.LIST_POINT_OF_INTEREST_ID AS LIST_POI1_2_0__, LISTCATEGO1_.LIST_CATEGORY_ID AS LIST_CAT2_2_0__ FROM POINT_OF_INTERES POINTOFINT0_ INNER JOIN POINT_OF_INTERES_LIST_CATEGORY LISTCATEGO1_ ON POINTOFINT0_.ID=LISTCATEGO1_.LIST_POINT_OF_INTEREST_ID INNER JOIN CATEGORY CATEGORY2_ ON LISTCATEGO1_.LIST_CATEGORY_ID=CATEGORY2_.ID CROSS JOIN POINT_OF_INTERES_LIST_CATEGORY LISTCATEGO3_, CATEGORY CATEGORY4_ WHERE POINTOFINT0_.ID=LISTCATEGO3_.LIST_POINT_OF_INTEREST_ID AND LISTCATEGO3_.LIST_CATEGORY_ID=CATEGORY4_.ID AND (? IN (.[*]))"; expected "NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
select pointofint0_.id as id1_1_0_, category2_.id as id1_0_1_, pointofint0_.cover_photo as cover_ph2_1_0_, pointofint0_.date as date3_1_0_, pointofint0_.description as descript4_1_0_, pointofint0_.location as location5_1_0_, pointofint0_.name as name6_1_0_, pointofint0_.photo2 as photo7_1_0_, pointofint0_.photo3 as photo8_1_0_, category2_.name as name2_0_1_, listcatego1_.list_point_of_interest_id as list_poi1_2_0__, listcatego1_.list_category_id as list_cat2_2_0__ from point_of_interes pointofint0_ inner join point_of_interes_list_category listcatego1_ on pointofint0_.id=listcatego1_.list_point_of_interest_id inner join category category2_ on listcatego1_.list_category_id=category2_.id cross join point_of_interes_list_category listcatego3_, category category4_ where pointofint0_.id=listcatego3_.list_point_of_interest_id and listcatego3_.list_category_id=category4_.id and (? in (.)) [42001-200]
2021-12-19 12:14:26 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1297)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2021-12-19 12:15:07 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Supherum/Desktop/TRIANA-TOURIST/triana-tourist/db/basededatos.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1297)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
